services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-api:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: